<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>Fexxo.FiscalGateway</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../source/.NET Standard/Unimake.Business.DFe/Unimake.Business.DFe.csproj" />
  </ItemGroup>

</Project>
